language: python

# Run jobs on container-based infrastructure, can be overridden per job
dist: trusty

#matrix:
#  include:
#    # Extra includes for OSX since python language is not available by default on OSX
#    - os: osx
#      language: generic
#      env: PYTHON_VER=3.5
#    - os: osx
#      language: generic
#      env: PYTHON_VER=3.6
#
#    - os: linux
#      python: 3.5
#      env: PYTHON_VER=3.5
#    - os: linux
#      python: 3.6
#      env: PYTHON_VER=3.6
env:
  matrix:
    - python=3.5 CONDA_PY=3.5
    - python=3.6 CONDA_PY=3.6

  global:
    - ORGNAME="omnia"
    - PACKAGENAME="mpiplus"

before_install:
    # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a

    # Install the Python environment
  - source devtools/travis-ci/before_install.sh
  - python -V

install:

    # Create test environment for package
  - conda create -n test python=$PYTHON_VER pip pytest pytest-cov "numpy>=1.11" 
  - conda activate test
  - conda config --add channels conda-forge
    # Add omnia channel
    # omina is prepended so coverage is installed from conda-forge
  - conda config --append channels omnia 
    # Add omnia dev channels
    # - if [ $DEVOMNIA ]; then conda config --add channels https://conda.anaconda.org/omnia/label/dev; fi

    # Install pip only modules
  - pip install codecov

    # Build and install package
  - conda build --python=$PYTHON_VER devtools/conda-recipe
  - conda install --use-local mpiplus


script:
  - pytest -v --cov=mpiplus mpiplus/tests/

notifications:
    email: false

after_success:
  - codecov
