package:
  name: mpiplus
  version: "0.0.0"

source:
  path: ../..

build:
  number: 0

requirements:
  host:
    - python
    - setuptools
    - coverage>=4.4
    - openmm>=7.1

  run:
    - python
    - numpy >=1.11

test:
  requires:
    - pytest
  imports:
    - mpiplus

about:
  home: add_url_here
  license: MIT License
