name: "CI"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    # At 07:00 UTC Everyday.
    - cron: "0 7 * * *"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  tests:
    runs-on: ${{ matrix.OS }}-latest
    name: "tests"
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu', 'macos']
        python-version:
          - "3.9"
          - "3.10"

    steps:
      - uses: actions/checkout@v3

      # More info on options: https://github.com/conda-incubator/setup-miniconda
      - name: Setup Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: environment.yml
          environment-name: mpiplus
          cache-env: true
          cache-downloads: true
          extra-specs: |
            python==${{ matrix.python-version }}

      - name: "Install"
        run: python -m pip install --no-deps -e .

      - name: "Test imports"
        run: |
          # if we add more to this, consider changing to for + env vars
          python -Ic "import mpiplus; print(mpiplus.__version__)"

      - name: "Environment Information"
        run: |
          micromamba info
          micromamba list

      - name: "Run tests"
        run: |
          pytest -n auto -v --cov=mpiplus --cov=mpiplus --cov-report=xml

      - name: codecov
        if: ${{ github.repository == 'choderalab/mpiplus'
                && github.event_name != 'schedule' }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
          fail_ci_if_error: False
          verbose: True
